### ISSUE TITLE
generating new environments

### ISSUE THREAD

**Issue by Abc12128** [robocasa/robocasa#87] opened 2024-10-08 13:25 UTC
Hi,Thank you so much for this great work.But now I have some ideas about generating new environments. If I want to create a new environment, such as a bedroom, a living room, etc., I need to expand the asset library to meet the needs of the new environment. Can you give me some good suggestions so that I can go more smoothly?
Please do not close the conversation after replying.Thank you for your understanding.

**Comment by snasiriany** [comment] 2024-10-08 14:25
Thanks for the feedback on issues. We still get notifications for replies, after the issue is closed. The team has just been busy in the past week.

Wanted to confirm with you - you don't see the button to re-open an issue even after the team has closed it?

I will re-open the previous issue and respond there later today.

**Closed by snasiriany** 2024-10-08 14:25 UTC
